"""
Bell-Spectrum Coupling Map (BSCM) Quantum Kernel.

A fidelity-based quantum kernel whose entangling layer is derived from the
uniform-prior Bell-projector decomposition of the two-qubit product state
|psi(x_i)> tensor |psi(x_j)> produced by the H * RZ(x) single-qubit
encoder.

Derivation (one-paragraph).
    For the encoder |psi(x)> = (e^{-ix/2}|0> + e^{ix/2}|1>) / sqrt(2),
    the four Bell-state weights of |psi(x_i)>|psi(x_j)> are
        w_{Phi+}  = (1/2) cos^2((x_i + x_j)/2)
        w_{Phi-}  = (1/2) sin^2((x_i + x_j)/2)
        w_{Psi+}  = (1/2) cos^2((x_i - x_j)/2)
        w_{Psi-}  = (1/2) sin^2((x_i - x_j)/2)
    SRQFM uses the singlet weight  w_{Psi-}  as an IsingZZ angle,
    discarding the other three sectors.  BSCM uses *all four* sectors
    with uniform prior weight by defining
        H_{ij}(x_i, x_j) = sum_k  (2 * w_k(x_i, x_j))  |k><k|.
    Substituting Bell projectors in the Pauli basis collapses to
        H_{ij} = (1/2) I + (1/2) cos x_i cos x_j  X_i X_j
                       + (1/2) sin x_i sin x_j  Y_i Y_j.
    The Z_i Z_j coefficient is identically zero (verified by
    scripts/verify_bscm_derivation.py, P2).  This makes BSCM a strict
    Pauli-orthogonal complement of any SRQFM coupling.

The kernel evaluation is the standard fidelity readout
    K(x, x') = | <psi(x') | psi(x)> |^2
            = | <0...0 | U^dagger(x') U(x) | 0...0> |^2
where U(x) is the BSCM feature map circuit (H, RZ(x), then per-pair
BSCM unitaries) repeated `reps` times.

Kernel time evolution is governed by a single hyperparameter `tau`
(default 1.0), which scales the per-pair generators uniformly.  At
tau = 1.0 the per-pair effective rotation magnitude is bounded by
1/2 rad (P1), placing BSCM in the same well-bounded regime as
SRQFM v1 and avoiding gate-angle wrap.

References:
    - Havlicek et al., Nature 567, 209 (2019). ZZFeatureMap.
    - Huang et al., Nature Comm. 12, 2631 (2021). PQK.
    - Kadam et al. (this paper). SRQFM.
    - This module. BSCM.

Author: Prathamesh Kadam et al.
"""
from __future__ import annotations

import logging
import os
import sys
import time
from typing import List, Optional, Tuple

import numpy as np
from tqdm import tqdm

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import config

logger = logging.getLogger(__name__)


# ============================================================================
# Coupling Hamiltonian
# ============================================================================

# Named Bell-prior weight presets.  Order: (w_{Phi+}, w_{Phi-}, w_{Psi+}, w_{Psi-}).
BELL_WEIGHT_PRESETS = {
    # Canonical BSCM: uniform prior over the 4 Bell sectors.  Yields
    # H = (1/2) I + (1/2) cos x_i cos x_j  XX + (1/2) sin x_i sin x_j  YY,
    # ZZ coefficient identically zero (single-pair P2).
    "uniform": (1.0, 1.0, 1.0, 1.0),
    # Even-parity (Phi) sector only: emphasises the |Phi+>, |Phi-> subspace.
    # H_pair has feature-dependent coefficient on (XX - YY) (pair creation),
    # constant ZZ (no feature-dependent ZZ entanglement).
    "phi_only": (2.0, 2.0, 0.0, 0.0),
    # Odd-parity (Psi) sector only: emphasises the |Psi+>, |Psi-> subspace.
    # H_pair has equal feature-dependent coefficients on (XX + YY) (hopping),
    # constant ZZ.
    "psi_only": (0.0, 0.0, 2.0, 2.0),
}


def bscm_pauli_coefficients(
    x_i: float, x_j: float,
    weights: Tuple[float, float, float, float] = BELL_WEIGHT_PRESETS["uniform"],
) -> Tuple[float, float, float]:
    """Per-pair Pauli coefficients (alpha_XX, alpha_YY, alpha_ZZ) in the
    Hamiltonian generated by Bell-projector weights `weights`.

    H_{ij}(x_i, x_j; w) = sum_k w_k * (Bell amplitude)_k * |Bell_k><Bell_k|
                        = (alpha_II) I + alpha_XX XX + alpha_YY YY + alpha_ZZ ZZ.

    The Bell-amplitude weights are
        c_plus  = cos^2((x_i + x_j)/2)
        s_plus  = sin^2((x_i + x_j)/2)
        c_minus = cos^2((x_i - x_j)/2)
        s_minus = sin^2((x_i - x_j)/2)
    and the closed-form Pauli coefficients (from the |Bell><Bell| =
    Pauli expansion) are returned.

    For weights = (1, 1, 1, 1) (uniform):
        alpha_XX = (1/2) cos x_i cos x_j
        alpha_YY = (1/2) sin x_i sin x_j
        alpha_ZZ = 0  (P2)
    """
    w1, w2, w3, w4 = weights
    cp = np.cos((x_i + x_j) / 2.0) ** 2
    sp = np.sin((x_i + x_j) / 2.0) ** 2
    cm = np.cos((x_i - x_j) / 2.0) ** 2
    sm = np.sin((x_i - x_j) / 2.0) ** 2
    a_xx = (w1 * cp - w2 * sp + w3 * cm - w4 * sm) / 4.0
    a_yy = (-w1 * cp + w2 * sp + w3 * cm - w4 * sm) / 4.0
    a_zz = (w1 * cp + w2 * sp - w3 * cm - w4 * sm) / 4.0
    return float(a_xx), float(a_yy), float(a_zz)


def bscm_xy_coefficients(x_i: float, x_j: float) -> Tuple[float, float]:
    """Backward-compatible accessor: returns (alpha_XX, alpha_YY) for the
    canonical uniform-prior BSCM.  Equivalent to
    bscm_pauli_coefficients(x_i, x_j)[:2] when weights == 'uniform'.
    """
    a_xx, a_yy, _ = bscm_pauli_coefficients(x_i, x_j)
    return a_xx, a_yy


def coupling_strength(
    x_i: float, x_j: float,
    weights: Tuple[float, float, float, float] = BELL_WEIGHT_PRESETS["uniform"],
) -> float:
    """Scalar coupling strength for sparsification: max(|a_XX|, |a_YY|, |a_ZZ|)."""
    a, b, c = bscm_pauli_coefficients(x_i, x_j, weights)
    return max(abs(a), abs(b), abs(c))


# ============================================================================
# BSCM Feature Map Circuit
# ============================================================================

def _resolve_pairs(n_qubits: int, connectivity: str) -> List[Tuple[int, int]]:
    if connectivity == "all":
        return [(i, j) for i in range(n_qubits) for j in range(i + 1, n_qubits)]
    if connectivity == "linear":
        return [(i, i + 1) for i in range(n_qubits - 1)]
    if connectivity == "cross":
        mid = n_qubits // 2
        return [(i, j) for i in range(mid) for j in range(mid, n_qubits)]
    raise ValueError(f"Unknown connectivity: {connectivity}")


def apply_bscm_feature_map(
    x: np.ndarray,
    n_qubits: int = config.N_QUBITS,
    reps: int = config.ZZ_REPS,
    tau: float = 1.0,
    coupling_threshold: float = 1e-4,
    connectivity: str = "all",
    bell_weights: Tuple[float, float, float, float]
        = BELL_WEIGHT_PRESETS["uniform"],
    singlet_gated: bool = False,
) -> None:
    """Apply U(x) = product of BSCM layers, in-place inside a QNode.

    Per layer:
        1. H on every qubit.
        2. RZ(x_i) on every qubit (single-qubit feature encoding).
        3. For each pair (i, j) in the connectivity, apply
             IsingXX( 2 * tau * a_xx )
             IsingYY( 2 * tau * a_yy )
             IsingZZ( 2 * tau * a_zz )
           where (a_xx, a_yy, a_zz) = bscm_pauli_coefficients(x_i, x_j; w).
           XX, YY, ZZ all commute pairwise on the same two qubits, so the
           gate order within a pair is irrelevant.

    For the canonical 'uniform' Bell-prior, a_zz is identically zero and
    only IsingXX, IsingYY are emitted.  Non-uniform priors generate a
    feature-dependent ZZ component, providing ablation control.

    Singlet gating (singlet_gated=True):
        Multiplies each pair's Pauli coefficients by the singlet fraction
        w_{Psi-} = sin^2((x_i - x_j) / 2).  This suppresses entanglement
        between qubits encoding similar feature values (x_i ~ x_j),
        preventing kernel concentration on correlated feature sets while
        preserving the BSCM XX+YY Pauli structure.
    """
    import pennylane as qml

    pairs = _resolve_pairs(n_qubits, connectivity)

    for _ in range(reps):
        for i in range(n_qubits):
            qml.Hadamard(wires=i)
        for i in range(n_qubits):
            qml.RZ(x[i], wires=i)
        for qi, qj in pairs:
            a_xx, a_yy, a_zz = bscm_pauli_coefficients(
                x[qi], x[qj], bell_weights
            )
            # Singlet-gated BSCM: modulate by the singlet fraction.
            if singlet_gated:
                sg = float(np.sin((x[qi] - x[qj]) / 2.0) ** 2)
                a_xx *= sg
                a_yy *= sg
                a_zz *= sg
            if max(abs(a_xx), abs(a_yy), abs(a_zz)) < coupling_threshold:
                continue
            if abs(a_xx) >= coupling_threshold:
                qml.IsingXX(2.0 * tau * a_xx, wires=[qi, qj])
            if abs(a_yy) >= coupling_threshold:
                qml.IsingYY(2.0 * tau * a_yy, wires=[qi, qj])
            if abs(a_zz) >= coupling_threshold:
                qml.IsingZZ(2.0 * tau * a_zz, wires=[qi, qj])


def apply_bscm_feature_map_adjoint(
    x: np.ndarray,
    n_qubits: int = config.N_QUBITS,
    reps: int = config.ZZ_REPS,
    tau: float = 1.0,
    coupling_threshold: float = 1e-4,
    connectivity: str = "all",
    bell_weights: Tuple[float, float, float, float]
        = BELL_WEIGHT_PRESETS["uniform"],
    singlet_gated: bool = False,
) -> None:
    """Apply U^dagger(x) by reversing the gate ordering and negating angles."""
    import pennylane as qml

    pairs = _resolve_pairs(n_qubits, connectivity)

    for _ in range(reps):
        for qi, qj in reversed(pairs):
            a_xx, a_yy, a_zz = bscm_pauli_coefficients(
                x[qi], x[qj], bell_weights
            )
            if singlet_gated:
                sg = float(np.sin((x[qi] - x[qj]) / 2.0) ** 2)
                a_xx *= sg
                a_yy *= sg
                a_zz *= sg
            if max(abs(a_xx), abs(a_yy), abs(a_zz)) < coupling_threshold:
                continue
            if abs(a_zz) >= coupling_threshold:
                qml.IsingZZ(-2.0 * tau * a_zz, wires=[qi, qj])
            if abs(a_yy) >= coupling_threshold:
                qml.IsingYY(-2.0 * tau * a_yy, wires=[qi, qj])
            if abs(a_xx) >= coupling_threshold:
                qml.IsingXX(-2.0 * tau * a_xx, wires=[qi, qj])
        for i in range(n_qubits - 1, -1, -1):
            qml.RZ(-x[i], wires=i)
        for i in range(n_qubits - 1, -1, -1):
            qml.Hadamard(wires=i)


# ============================================================================
# Fidelity Kernel
# ============================================================================

def _build_fidelity_circuit(
    n_qubits: int,
    reps: int,
    tau: float,
    coupling_threshold: float,
    connectivity: str,
    bell_weights: Tuple[float, float, float, float] = BELL_WEIGHT_PRESETS["uniform"],
    singlet_gated: bool = False,
):
    """Construct the QNode that computes |<0...0| U^dagger(x2) U(x1) |0...0>|^2."""
    import pennylane as qml

    dev = config.get_device(n_qubits)

    @qml.qnode(dev, diff_method=None)
    def circuit(x1, x2):
        apply_bscm_feature_map(
            x1, n_qubits, reps, tau, coupling_threshold, connectivity,
            bell_weights, singlet_gated,
        )
        apply_bscm_feature_map_adjoint(
            x2, n_qubits, reps, tau, coupling_threshold, connectivity,
            bell_weights, singlet_gated,
        )
        return qml.probs(wires=range(n_qubits))

    return circuit


def compute_bscm_fidelity_kernel(
    X: np.ndarray,
    X2: Optional[np.ndarray] = None,
    n_qubits: int = config.N_QUBITS,
    reps: int = config.ZZ_REPS,
    tau: float = 1.0,
    coupling_threshold: float = 1e-4,
    connectivity: str = "all",
    bell_weights: Tuple[float, float, float, float]
        = BELL_WEIGHT_PRESETS["uniform"],
    kernel_save_path: Optional[str] = None,
    desc: str = "BSCM",
    singlet_gated: bool = False,
) -> np.ndarray:
    """Compute the BSCM fidelity kernel matrix.

    For X2 is None this returns the symmetric N x N Gram matrix using
    upper-triangle symmetry (only N (N+1)/2 circuit evaluations).  For
    X2 not None it returns an M x N rectangular matrix.

    Caching: if `kernel_save_path` exists on disk it is loaded and
    returned; otherwise the computed matrix is saved at that path.

    If singlet_gated=True, the singlet-fraction modulation
    sin^2((x_i - x_j)/2) is applied to every pair's Pauli coupling
    coefficients before emitting Ising gates.  See
    apply_bscm_feature_map() for details.
    """
    if kernel_save_path is not None and os.path.exists(kernel_save_path):
        logger.info(f"[CACHE] Loading BSCM kernel from {kernel_save_path}")
        return np.load(kernel_save_path)

    circuit = _build_fidelity_circuit(
        n_qubits, reps, tau, coupling_threshold, connectivity,
        bell_weights, singlet_gated,
    )

    if kernel_save_path is not None:
        os.makedirs(os.path.dirname(kernel_save_path), exist_ok=True)

    n = len(X)
    if X2 is None:
        # Row-level checkpointing for crash recovery on multi-hour runs.
        # We save the partially-filled K and a `next_i` marker after each row.
        ckpt_path = (kernel_save_path + ".ckpt.npz") if kernel_save_path else None
        start_i = 0
        if ckpt_path is not None and os.path.exists(ckpt_path):
            ck = np.load(ckpt_path)
            if ck["n"].item() == n:
                K = ck["K"].copy()
                start_i = int(ck["next_i"].item())
                logger.info("[CKPT] Resuming %s from row %d/%d", desc, start_i, n)
            else:
                K = np.ones((n, n), dtype=np.float64)
        else:
            K = np.ones((n, n), dtype=np.float64)

        n_evals_total = n * (n - 1) // 2
        n_evals_done = start_i * n - start_i * (start_i + 1) // 2
        pbar = tqdm(total=n_evals_total, desc=f"{desc} K({n}x{n})", unit="eval",
                    initial=n_evals_done)
        for i in range(start_i, n):
            for j in range(i + 1, n):
                p0 = float(circuit(X[i], X[j])[0])
                K[i, j] = p0
                K[j, i] = p0
                pbar.update(1)
            if ckpt_path is not None and ((i + 1) % 25 == 0 or i == n - 1):
                np.savez(ckpt_path, K=K, next_i=np.array(i + 1), n=np.array(n))
        pbar.close()
    else:
        m = len(X2)
        K = np.zeros((m, n), dtype=np.float64)
        pbar = tqdm(total=m * n, desc=f"{desc} K({m}x{n})", unit="eval")
        for i in range(m):
            for j in range(n):
                K[i, j] = float(circuit(X[j], X2[i])[0])
                pbar.update(1)
        pbar.close()

    if kernel_save_path is not None:
        os.makedirs(os.path.dirname(kernel_save_path), exist_ok=True)
        np.save(kernel_save_path, K)
        logger.info(f"Saved BSCM kernel to {kernel_save_path}")
        ckpt_path = kernel_save_path + ".ckpt.npz"
        try:
            if os.path.exists(ckpt_path):
                os.remove(ckpt_path)
        except OSError:
            pass  # Windows occasionally holds the file briefly; non-critical.

    return K


# ============================================================================
# Projected Quantum Kernel (PQK) — Bloch-Vector Extraction
# ============================================================================

def extract_bscm_bloch_vectors(
    X: np.ndarray,
    n_qubits: int = config.N_QUBITS,
    reps: int = config.ZZ_REPS,
    tau: float = 1.0,
    coupling_threshold: float = 1e-4,
    connectivity: str = "all",
    bell_weights: Tuple[float, float, float, float]
        = BELL_WEIGHT_PRESETS["uniform"],
    singlet_gated: bool = False,
    cache_path: Optional[str] = None,
    desc: str = "BSCM-PQK",
) -> np.ndarray:
    """Extract per-qubit Bloch vectors from the BSCM feature-map circuit.

    For each sample x, runs U(x)|0...0⟩ (the *forward* feature map only —
    no adjoint) and measures the three single-qubit Pauli expectations
    ⟨X_q⟩, ⟨Y_q⟩, ⟨Z_q⟩ on each qubit q.

    This is the "Projected Quantum Kernel" (PQK) approach of Huang et al.
    (Nature Comm. 2021): instead of computing the fidelity |⟨ψ(x')|ψ(x)⟩|²
    (which requires N² circuit pairs), we extract a 3·n_q–dimensional
    classical feature vector per sample (N circuit executions total), then
    build a classical RBF kernel on these vectors.

    The BSCM variant uses the XX+YY entangling layer (with optional
    singlet gating) rather than SRQFM's ZZ layer, so the Bloch vectors
    encode different inter-qubit correlations — specifically, the X and Y
    components carry information from the non-commuting IsingXX/IsingYY
    channels that fidelity-based BSCM would squash via concentration.

    Args:
        X:            (N, n_qubits) encoded feature matrix in [0, π].
        n_qubits:     Number of qubits (= feature dimension).
        reps:         Circuit repetitions.
        tau:          Time-evolution scaling.
        coupling_threshold: Minimum |coefficient| to emit a gate.
        connectivity: Qubit pair topology ("all", "linear", "cross").
        bell_weights: Bell-sector prior weights.
        singlet_gated: If True, multiply Pauli coefficients by the singlet
                       fraction sin²((x_i − x_j)/2) before gating.
        cache_path:   If set, save/load Bloch array to/from this .npy path.
        desc:         Progress bar label.

    Returns:
        (N, 3 * n_qubits) float64 array.  Layout per sample:
        [⟨X_0⟩, ⟨Y_0⟩, ⟨Z_0⟩, ⟨X_1⟩, ⟨Y_1⟩, ⟨Z_1⟩, ...].
    """
    import pennylane as qml

    # Cache check.
    if cache_path is not None and os.path.exists(cache_path):
        bloch = np.load(cache_path)
        expected_shape = (len(X), 3 * n_qubits)
        if bloch.shape == expected_shape:
            logger.info("[CACHE] Loaded Bloch vectors from %s", cache_path)
            return bloch
        logger.warning(
            "[CACHE] Shape mismatch %s vs %s — recomputing.",
            bloch.shape, expected_shape,
        )

    dev = config.get_device(n_qubits)

    # Build three QNodes: one per Pauli basis.
    # Each runs U(x)|0⟩ then measures ⟨σ_q⟩ on all qubits simultaneously.

    @qml.qnode(dev, diff_method=None)
    def _measure_pauli_x(x):
        apply_bscm_feature_map(
            x, n_qubits, reps, tau, coupling_threshold, connectivity,
            bell_weights, singlet_gated,
        )
        return [qml.expval(qml.PauliX(q)) for q in range(n_qubits)]

    @qml.qnode(dev, diff_method=None)
    def _measure_pauli_y(x):
        apply_bscm_feature_map(
            x, n_qubits, reps, tau, coupling_threshold, connectivity,
            bell_weights, singlet_gated,
        )
        return [qml.expval(qml.PauliY(q)) for q in range(n_qubits)]

    @qml.qnode(dev, diff_method=None)
    def _measure_pauli_z(x):
        apply_bscm_feature_map(
            x, n_qubits, reps, tau, coupling_threshold, connectivity,
            bell_weights, singlet_gated,
        )
        return [qml.expval(qml.PauliZ(q)) for q in range(n_qubits)]

    N = len(X)
    bloch = np.zeros((N, 3 * n_qubits), dtype=np.float64)

    t0 = time.time()
    for idx in tqdm(range(N), desc=f"{desc} Bloch (N={N})", unit="sample"):
        bx = np.asarray(_measure_pauli_x(X[idx]), dtype=np.float64)
        by = np.asarray(_measure_pauli_y(X[idx]), dtype=np.float64)
        bz = np.asarray(_measure_pauli_z(X[idx]), dtype=np.float64)
        for q in range(n_qubits):
            bloch[idx, 3 * q]     = bx[q]
            bloch[idx, 3 * q + 1] = by[q]
            bloch[idx, 3 * q + 2] = bz[q]

    elapsed = time.time() - t0
    logger.info(
        "%s Bloch extraction: %d samples in %.0f s (%.1f min)",
        desc, N, elapsed, elapsed / 60,
    )

    # Diagnostic: per-qubit Bloch-sphere magnitudes.
    # A fully mixed state has |b| = 0; a pure state has |b| = 1.
    mags = np.zeros(n_qubits)
    for q in range(n_qubits):
        mags[q] = np.sqrt(
            bloch[:, 3 * q] ** 2
            + bloch[:, 3 * q + 1] ** 2
            + bloch[:, 3 * q + 2] ** 2
        ).mean()
    logger.info(
        "  Bloch magnitudes per qubit: %s (mean=%.3f)",
        np.round(mags, 3).tolist(), float(mags.mean()),
    )

    if cache_path is not None:
        os.makedirs(os.path.dirname(cache_path), exist_ok=True)
        np.save(cache_path, bloch)
        logger.info("  Saved Bloch vectors to %s", cache_path)

    return bloch


def compute_bscm_pqk_gram(
    bloch: np.ndarray,
    n_qubits: int = config.N_QUBITS,
    gamma: float = config.PQK_GAMMA,
) -> np.ndarray:
    """Build the Projected Quantum Kernel gram matrix from Bloch vectors.

    K(x, x') = exp( -γ · ½ · Σ_q ||b_q(x) − b_q(x')||² )

    where b_q = (⟨X_q⟩, ⟨Y_q⟩, ⟨Z_q⟩) is the 3-component Bloch vector
    of qubit q after the feature-map circuit.

    The kernel is equivalent to an RBF kernel on the concatenated Bloch
    vectors, with the per-qubit L2 distances summed before exponentiation.

    Args:
        bloch:    (N, 3 * n_qubits) Bloch-vector array from
                  extract_bscm_bloch_vectors().
        n_qubits: Number of qubits.
        gamma:    RBF bandwidth parameter.

    Returns:
        (N, N) symmetric positive-definite gram matrix with unit diagonal.
    """
    N = len(bloch)
    b = bloch.reshape(N, n_qubits, 3)  # (N, n_q, 3)

    K = np.zeros((N, N), dtype=np.float64)
    for i in range(N):
        diff = b[i] - b                    # (N, n_q, 3)
        sq_dist = (diff * diff).sum(axis=2)  # (N, n_q)
        total_dist = 0.5 * sq_dist.sum(axis=1)  # (N,)
        K[i] = np.exp(-gamma * total_dist)

    np.fill_diagonal(K, 1.0)
    K = (K + K.T) / 2.0  # Enforce numerical symmetry.
    return K


# ============================================================================
# Coupling Diagnostics
# ============================================================================

def compute_coupling_diagnostics(
    X: np.ndarray,
    feature_names: Optional[List[str]] = None,
    n_qubits: int = config.N_QUBITS,
    bell_weights: Tuple[float, float, float, float]
        = BELL_WEIGHT_PRESETS["uniform"],
) -> dict:
    """Per-pair (alpha_XX, alpha_YY) statistics across a sample of inputs,
    computed under the configured Bell-prior `bell_weights`.

    Reports both Pauli coefficients separately, which is what makes BSCM
    qualitatively different from SRQFM's single coupling scalar.

    Bug fix (2026-05): previously this function unconditionally called
    `bscm_xy_coefficients`, which always uses the uniform prior, so the
    printed alpha/beta statistics did not reflect the actual phi_only or
    psi_only prior in use.  It now respects `bell_weights`.
    """
    n = len(X)
    pair_stats = {}
    for i in range(n_qubits):
        for j in range(i + 1, n_qubits):
            alphas = np.array(
                [bscm_pauli_coefficients(X[s, i], X[s, j], bell_weights)[0]
                 for s in range(n)]
            )
            betas = np.array(
                [bscm_pauli_coefficients(X[s, i], X[s, j], bell_weights)[1]
                 for s in range(n)]
            )
            name_i = feature_names[i] if feature_names else f"q{i}"
            name_j = feature_names[j] if feature_names else f"q{j}"
            key = f"{name_i}-{name_j}"
            pair_stats[key] = {
                "alpha_mean": float(alphas.mean()),
                "alpha_std": float(alphas.std()),
                "beta_mean": float(betas.mean()),
                "beta_std": float(betas.std()),
                "max_amp_mean": float(np.maximum(np.abs(alphas), np.abs(betas)).mean()),
                "qubits": (i, j),
            }
    overall = {
        "n_pairs": len(pair_stats),
        "n_samples": n,
        "global_alpha_mean": float(np.mean([v["alpha_mean"] for v in pair_stats.values()])),
        "global_beta_mean": float(np.mean([v["beta_mean"] for v in pair_stats.values()])),
        "pairs": pair_stats,
    }
    return overall


# ============================================================================
# Self-test
# ============================================================================

def _self_test() -> None:
    """Numerical validation of BSCM kernel structural properties.

    Tests:
        1. Coupling coefficient bounds:  |alpha|, |beta| <= 1/2.
        2. Boundary case x_i = x_j -> Hamiltonian is (1/2)I + (1/2) XX.
        3. Kernel symmetry:  K = K.T  (within numerical noise).
        4. Kernel diagonal:  K[i, i] = 1.
        5. Kernel PSD: smallest eigenvalue >= -tol.
        6. Numerical P2 on the circuit:  the fully-applied gate has zero
           ZZ Pauli component when measured as a 2-qubit unitary on a
           random pair.  (Sanity check that the implementation matches
           the derivation.)
    """
    import pennylane as qml

    print("=" * 60)
    print("  BSCM Kernel Self-Test")
    print("=" * 60)

    np.random.seed(config.RANDOM_SEED)
    n_q = 4
    N = 16
    X = np.random.rand(N, n_q) * np.pi

    # 1. Coefficient bounds.
    print("\n[1] Coupling coefficient bounds...")
    rng = np.random.default_rng(0)
    worst_a, worst_b = 0.0, 0.0
    for _ in range(10000):
        x_i, x_j = rng.uniform(-2 * np.pi, 2 * np.pi, size=2)
        a, b = bscm_xy_coefficients(x_i, x_j)
        worst_a = max(worst_a, abs(a))
        worst_b = max(worst_b, abs(b))
    assert worst_a <= 0.5 + 1e-12 and worst_b <= 0.5 + 1e-12
    print(f"  max |alpha| = {worst_a:.4f}    max |beta| = {worst_b:.4f}    OK.")

    # 2. Boundary x_i = x_j.
    print("\n[2] Boundary x_i = x_j ...")
    a, b = bscm_xy_coefficients(0.7, 0.7)
    assert abs(a - 0.5 * np.cos(0.7) ** 2) < 1e-12
    assert abs(b - 0.5 * np.sin(0.7) ** 2) < 1e-12
    assert abs((a + b) - 0.5) < 1e-12  # cos^2 + sin^2 = 1
    print(f"  alpha + beta = 1/2  for redundant features.  OK.")

    # 3. Kernel symmetry, diagonal, PSD.
    print(f"\n[3-5] Building BSCM kernel ({n_q} qubits, N={N})...")
    K = compute_bscm_fidelity_kernel(
        X, n_qubits=n_q, reps=2, tau=1.0,
        coupling_threshold=1e-4, connectivity="all",
    )
    asym = float(np.max(np.abs(K - K.T)))
    diag_err = float(np.max(np.abs(K.diagonal() - 1.0)))
    eig = np.linalg.eigvalsh((K + K.T) / 2)
    print(f"  asymmetry              = {asym:.2e}")
    print(f"  diagonal error         = {diag_err:.2e}")
    print(f"  min eigenvalue         = {eig.min():.6e}")
    assert asym < 1e-10
    assert diag_err < 1e-10
    assert eig.min() > -1e-8

    # 6. Numerical P2 on the circuit, single pair, single rep.
    print("\n[6] Numerical P2 on the circuit (single pair, single rep)...")
    dev = qml.device("default.qubit", wires=2)

    @qml.qnode(dev, diff_method=None)
    def pair_unitary_zz():
        # Apply one BSCM rep on a 2-qubit register, measure ZZ.
        x = np.array([0.7, 1.3])  # arbitrary
        apply_bscm_feature_map(
            x, n_qubits=2, reps=1, tau=1.0,
            coupling_threshold=1e-4, connectivity="all",
        )
        return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1))

    # The Hadamard layer + RZ layer alone produces <ZZ> = 0 on |00>:
    # H|0> = |+>; RZ doesn't change <Z> on |+>; so <Z_0> = <Z_1> = 0
    # and <Z_0 Z_1> = 0 (independent of tau and the IsingXX/IsingYY).
    val = float(pair_unitary_zz())
    print(f"  <ZZ> after BSCM layer = {val:.2e}   (expected ~0 by construction)")
    assert abs(val) < 1e-10

    print("\n" + "=" * 60)
    print("  ALL BSCM SELF-TESTS PASSED")
    print("=" * 60)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )
    _self_test()
